namespace: database
name: mysql
version: 1.0.0
readme: null
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  database.postgresql: '>=1.0'
repository: git@github.com:gundalow-collections/database
documentation: null
homepage: null
issues: null
